### ISSUE TITLE
Handling the RMM / RMA split

### ISSUE THREAD

**Issue by zimeon** [cul-it/cular-metadata#11]
In existing work with a "DEPOSITOR/COLLECTION" key, we have things like "RMC/RMM/RMM01234" which I assume is DEPOSITOR=RMC , COLLECTION=RMM/RMM01234. I understand there was some discussion about this in a previous meeting and note that we have some additional complexity in handling a collection that has some internal hierarchy in its name. Is that going to be used anywhere else? If not, should we consider just putting RMA or RMM in the place of RMC depositor? Or is the middle field not required anyway because all the collection names start with RMA or  RMM?

**Comment by bb233** [comment]
Based on the discussions we've had, I believe it's DEPOSITOR=RMC/RMM, COLLECTION=RMM01234. That would lead to two depositors, RMC/RMA and RMC/RMM. That was my intent when writing the manifest indexing code (not necessarily the practice; bugs are always a thing).

There may have been some talk about making those RMCRMM and RMCRMA or similar, non-slashy, pairing.

**Comment by dd388** [comment]
Here's an example of how it's described in a preingest for RMC: https://confluence.cornell.edu/x/O21OFQ

This suggests that the COLLECTION=RMM or COLLECTION=RMA and then third level component because the first element of the pathname. This will match CULAR Classic and our current organization on S3/SFS.

**Comment by dd388** [comment]
This doesn't totally solve the problem, actually...

I'm going to ask about the origins of the additional hierarchical structure and then report back.

**Comment by blaisepascal** [comment]
I believe in our discussions RMC was unusual in that it had a subdivision at the depositor level. Everything else worked for a two-level structure. So we are talking about either how to deal with the special case of RMC, or how to generalize the RMC use-case.

**Comment by zimeon** [comment]
Closing this because the [current proposal](https://github.com/cul-it/cular-metadata/blob/master/new_manifest_proposal.md) doesn't use COLLECTION as a directory component in storage and the decision is anyway to avoid the duplication because the collection name is really just "RMM/RMM01234" and not "RMM01234"
