### ISSUE TITLE
Need definition for `rmcmediano`

### ISSUE THREAD

**Issue by zimeon** [cul-it/cular-metadata#12]
https://github.com/cul-it/cular-metadata/blob/56fcc22ae6c2de1e4e7d2c321907cf7639728b42/new_manifest_proposal.json#L21

Can and should this idea of collection-specific ids be generalized? Is it likely to happen for other collections?

I also note that the naming doesn't follow either snake or camelcase conventions

**Comment by bb233** [comment]
I think that having a collection of identifiers would be an extensible generalization. Currently we have rmcmediano and bibid off the top of my head, neither of which I think are required or unique. Having a section like:
~~~~
"collection_ids" = [ 
    "rmd_media_no": ..., 
    "bibid": ...
]
~~~~

I would have to think about the best way to index, store, and display them, but it should be doable.

**Comment by dd388** [comment]
```
"item_ids" : { 
    "bibid": ...,
    "rmc": ...
}
```

Let's call this "rmc" so that it is a general field for any RMC item identifier.

**Comment by zimeon** [comment]
In the [current proposal](https://github.com/cul-it/cular-metadata/blob/master/new_manifest_proposal.md) we have `bibid` and `rmcmediano` as properties associated with a package. I think it would avoid introducing the word "item" as that has specific meaning in RMC that does not always correspond with package. However, question that remains is whether a package has specific propeties:

```
  "package_id": ...,
  "bibid": ...,
  "rmcmediano": ...,
```

or a generalized set of alternate/other ids, perhaps:

```
  "package_id": ...,
  "alternate_ids": {
     "bibid": ...,
     "rmc": ...
  },
```

**Comment by zimeon** [comment]
In https://github.com/cul-it/cular-metadata/blob/master/new_manifest_proposal.md the `rmcmediano` is to be included if available, used only by RMC.
