### ISSUE TITLE
File with colon renders repository unable to be cloned in Windows

### ISSUE THREAD

**Issue by dd388** [cul-it/cular-metadata#16]
My clone of the repository on Windows keeps breaking because of this example file:

https://github.com/cul-it/cular-metadata/tree/master/examples/urn:uuid:f81d4fae-7dec-11d0-a765-00a0c91e6bf6

**Comment by zimeon** [comment]
Not sure why we need to call the example directory the exact URI, changed colons to hyphens in 2bc1e74d768657adecaeb18f13ad1a590f170071
