### ISSUE TITLE
Propose changing rmcmediano to depositor_id

### ISSUE THREAD

**Issue by dd388** [cul-it/cular-metadata#18]
I propose we change the label `rmcmediano` within the packages array to be `depositor_id` to have a more generalize-able structure for the JSON across multiple collections and various depositors.

We do specify `bibid` as a specific identifier in the packages section; however, I think that is general enough to apply to RMC collections. (There are Voyager records for RMC records, at the collection level.)

**Comment by zimeon** [comment]
Would `depositors_id` or something else be less apt to be confused with the id of the depositor?

**Comment by dd388** [comment]
I'm not wedded to the exact label but I would like a way to express an identifier that is internal or local to the depositor.

**Comment by zimeon** [comment]
`local_id` ?

**Comment by dd388** [comment]
That would work for me.

**Comment by bb233** [comment]
Is it semantically meaningful to have multiple `local_id`'s?

**Comment by dd388** [comment]
`local_id` is in use; closing this issue.
