### ISSUE TITLE
Each file-level object should have a unique identifier

### ISSUE THREAD

**Issue by blaisepascal** [cul-it/cular-metadata#8]
In the new_manifest_proposal.json file, it would be useful if each file had assigned a unique identifier, or if a specified formula was given to calculate one (such as the MD5 of the collection, path, and filename).

This identifier would be useful for indexing.

**Comment by zimeon** [comment]
I don't think it would be sensible to create and maintain an id for the purpose of indexing since one can be generated in other ways. (trivially: depositor/collection/path/filename as you point out)

**Comment by zimeon** [comment]
The [current proposal](https://github.com/cul-it/cular-metadata/blob/master/new_manifest_proposal.md) emphasizes packages and unique package identifiers as the key to connecting data (packages) in archival storage and metadata (about packages and their contents) in ArchivesSpace. The identifier for a file-level object will be a combination of the `package_id` and `path/filename` for the file.
