### ISSUE TITLE
Split collection field into separate depositor and collection fields.

### ISSUE THREAD

**Issue by blaisepascal** [cul-it/cular-metadata#9]
A single field shouldn't, generally, contain two bits of data. Splitting the collection field into depositor and collection would align our usage to that guideline.

Since this data is stored at the collection level, not the file level, making this split will not impact manifest size very much.

**Comment by zimeon** [comment]
Agreed, we should probably think about the names for these fields but to stick with convention so far I'll split into two fields so that is no splitting stings on '/'...
